# CI name
name: Run linters and specs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  suite:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node on the runner
        uses: actions/setup-node@v3
        with:
          node-version: 19.x

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Prettier Formatting
        run: npm run format:fix

      - name: Run Prettier Check
        run: npm run format:check

      
